lib/towwwer_web/router.ex
defmodule TowwwerWeb.Router do
  use TowwwerWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug PlugEtsCache.Plug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TowwwerWeb do
    pipe_through :browser

    get "/", SiteController, :index
    get "/insights", PageController, :insights
    resources "/sites", SiteController
    # resources "/monitors", MonitorController, only: [:show]
    # resources "/reports", ReportController, only: [:show]
  end

  # Other scopes may use custom stacks.
  scope "/api", TowwwerWeb, as: :api do
    pipe_through :api

    scope "/v1", V1, as: :v1 do
      resources "/sites", SiteController, except: [:new, :edit]
      resources "/monitors", MonitorController, except: [:new, :edit]
      resources "/reports", ReportController, except: [:new, :edit]
    end
  end
end

lib/towwwer_web/views/layout_view.ex
defmodule TowwwerWeb.LayoutView do
  use TowwwerWeb, :view

  def active_class(conn, path) do
    current_path = Path.join(["/" | conn.path_info])

    if path == current_path do
      "is-active"
    else
      nil
    end
  end
end

lib/towwwer_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Towwwer · Automated performance, SEO and accessibility monitoring for websites</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
  </head>
  <body>
    <header class="l-site-navigation">
      <h3 class="c-site-logo"><%= link "Towwwer", to: Routes.site_path(@conn, :index) %></h3>
      <ul class="c-site-navigation">
        <li class="c-site-navigation__item <%= active_class(@conn, Routes.site_path(@conn, :index)) %>">
          <%= link "Performance", to: Routes.site_path(@conn, :index) %>
        </li>
        <li class="c-site-navigation__item <%= active_class(@conn, Routes.page_path(@conn, :insights)) %>">
          <%= link "Security", to: Routes.page_path(@conn, :insights) %>
        </li>
      </ul>
    </header>

    <div class="l-site-container">
      <div class="l-site-content">
        <div class="c-site-content">
          <p class="c-alert c-alert--positive" role="alert"><%= get_flash(@conn, :info) %></p>
          <p class="c-alert c-alert--negative" role="alert"><%= get_flash(@conn, :error) %></p>
          <%= render @view_module, @view_template, assigns %>
        </div>
      </div>
    </div>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>